### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by quangntenemy** [danielpclark/abrute#31]
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead?
  --> src/main.rs:41:1
   |
41 | extern crate libc;
   | ^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #27812 <https://github.com/rust-lang/rust/issues/27812> for more information
   = help: add `#![feature(rustc_private)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead?
  --> src/main.rs:42:5
   |
42 | use libc::pthread_cancel;
   |     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #27812 <https://github.com/rust-lang/rust/issues/27812> for more information
   = help: add `#![feature(rustc_private)]` to the crate attributes to enable

warning: use of deprecated item 'std::sync::atomic::ATOMIC_USIZE_INIT': the `new` function is now preferred
  --> src/main.rs:51:3
   |
51 |   ATOMIC_USIZE_INIT,
   |   ^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated item 'std::sync::atomic::ATOMIC_BOOL_INIT': the `new` function is now preferred
  --> src/main.rs:52:3
   |
52 |   ATOMIC_BOOL_INIT
   |   ^^^^^^^^^^^^^^^^

warning: use of deprecated item 'std::sync::atomic::ATOMIC_USIZE_INIT': the `new` function is now preferred
  --> src/main.rs:55:34
   |
55 | static ITERATIONS: AtomicUsize = ATOMIC_USIZE_INIT;
   |                                  ^^^^^^^^^^^^^^^^^ help: replace the use of the deprecated item: `AtomicUsize::new(0)`

warning: use of deprecated item 'std::sync::atomic::ATOMIC_BOOL_INIT': the `new` function is now preferred
  --> src/main.rs:56:30
   |
56 | static SUCCESS: AtomicBool = ATOMIC_BOOL_INIT;
   |                              ^^^^^^^^^^^^^^^^ help: replace the use of the deprecated item: `AtomicBool::new(false)`

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead?
   --> src/main.rs:270:5
    |
270 |     pthread_cancel(wr);
    |     ^^^^^^^^^^^^^^
    |
    = note: see issue #27812 <https://github.com/rust-lang/rust/issues/27812> for more information
    = help: add `#![feature(rustc_private)]` to the crate attributes to enable

warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
  --> src/main.rs:62:12
   |
62 |     author(crate_authors!("\n")).
   |            ^^^^^^^^^^^^^^^^^^^^
   |
   = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
  --> src/main.rs:62:12
   |
62 |     author(crate_authors!("\n")).
   |            ^^^^^^^^^^^^^^^^^^^^
   |
   = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: use of deprecated item 'std::error::Error::description': use the Display impl or to_string()
   --> src/main.rs:288:15
    |
288 |           err.description()
    |               ^^^^^^^^^^^

error: aborting due to 3 previous errors; 7 warnings emitted

For more information about this error, try `rustc --explain E0658`.
error: could not compile `abrute`.

To learn more, run the command again with --verbose.

**Comment by danielpclark** [comment]
Hey @quangntenemy , thanks for this report.  I don't get notifications unless I'm tagged so I just found this.

**Comment by danielpclark** [comment]
@quangntenemy I've updated the deprecations that Rust has since added and pushed a new version of v0.1.9
