### ISSUE TITLE
Not working anymore - error: Found argument which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by oom-** [danielpclark/abrute#32]
I do not succeed to start it on Fedora:
`uname -a` : `Linux 3061f96ef03c 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
![image](https://user-images.githubusercontent.com/11071671/218220644-68a8fe32-bb34-4173-8554-6c9d28c3d643.png)

**Comment by VexAzomi** [comment]
I had this issue aswell. I have no experience with rust, but I modified the source code in a quick and dirty attempt
(in main.rs)
and well now i can supply the TARGET arg like an option.
i.e.: abrute 4 abcdefghi... -f ./text.txt.aes

![image](https://github.com/danielpclark/abrute/assets/123071956/a34a7a8e-aaff-4b37-ac7e-2e1da6a27e7c)

![image](https://github.com/danielpclark/abrute/assets/123071956/f290043a-34d7-41af-903f-90431107b0f5)

**Comment by danielpclark** [comment]
There were some issues with the CLI library.  The fix is released as of today.
