### ISSUE TITLE
Create install script

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/abrute#7]
Create a `sh` friendly install script that will also install `aescrypt` with this package if it's not already installed.

The aescrypt license permits a binary to be packaged with it and it currently resides in this repositories `bin` directory.  It would be nicer to not have the binary in this repo and have this provide a pure install from each source.

The install script should work in the same form factor as Rust's `rustup` script

```
curl https://sh.rustup.rs -sSf | sh
```

**UPDATE**

This is how the install script flow should go.

* First — check if Rust is installed or not.  If it is installed skip to next step.  If not notify the user that Rust needs to be installed to continue and ask if they want to continue.  If they say yes install Rust.  If no stop the installation.
* Second — check is aescrypt is installed or not.  If not install it.
* Third — download abrute source code, run `cargo build release` and `sudo cp target/release/abrute /usr/bin/`
* Fourth — Say “Thank you for installing abrute!  Enjoy!”

**Comment by baptistecolin** [comment]
let me see what I can do
